server:
  port: 8090
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    discovery:
      client:
        simple:
          local:
            instance-id:

#server-url:
#  service-provider: http://service-provider

